name: Build sagemaker-code-editor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DISABLE_V8_COMPILE_CACHE: 1

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc g++ libx11-dev xorg-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python3 jq perl gettext automake autoconf quilt
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build vscode
        run: |
          cd vscode
          export DISABLE_V8_COMPILE_CACHE=1
          export NODE_OPTIONS="--max-old-space-size=4096"
          export UV_THREADPOOL_SIZE=4
          npm i -g node-gyp
          yarn install --network-concurrency 1
          VSCODE_RIPGREP_VERSION=$(jq -r '.dependencies."@vscode/ripgrep"' package.json)
          mv package.json package.json.orig
          jq 'del(.dependencies."@vscode/ripgrep")' package.json.orig > package.json
          yarn install
          yarn add --ignore-scripts "@vscode/ripgrep@${VSCODE_RIPGREP_VERSION}"
          ARCH_ALIAS=linux-x64
          yarn gulp vscode-reh-web-${ARCH_ALIAS}-min
      - name: Package built vscode
        run: |
          tar czf vscode-reh-web-linux-x64.tar.gz -C vscode vscode-reh-web-linux-x64
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-reh-web-linux-x64
          path: vscode-reh-web-linux-x64.tar.gz