name: Automated Release

# Controls when the workflow will run
on:
  # Triggers the workflow on updates to the "main" branch which include a version tag
  push:
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

env:
  branch-name: automated-dev-update
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag is version tag
        id: check
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            REF="${{ github.ref }}"
            VERSION="${REF##refs/tags/v}"
            echo "Tag starts with 'v'."
            echo "Version: ${VERSION}"
            echo "Continuing..."
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "The tag doesn't start with 'v'. To release a new version, the tag must start with 'v'"
            exit 1
          fi
    outputs:
      version: ${{ steps.check.outputs.version }}
      
  release:
    environment: release
    runs-on: ubuntu-latest
    needs: [check-tag]
    container:
      image: node:20
    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3 quilt
      - name: Build Tarball
        id: build
        run: |
          git config --global --add safe.directory /__w/sagemaker-code-editor/sagemaker-code-editor
          sh ./scripts/install.sh -t ${{ needs.check-tag.outputs.version }}
          
          TARBALL_NAME="code-editor${{ needs.check-tag.outputs.version }}.tar.gz"
          echo "tarball_name=${TARBALL_NAME}" >> $GITHUB_OUTPUT
          
          SHA256_HASH=$(sha256sum ${TARBALL_NAME} | awk '{ print $1 }')
          echo "sha256_hash=${SHA256_HASH}" >> $GITHUB_OUTPUT
      - name: Publish Release
        id: publish
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: Code Editor ${{ needs.check-tag.outputs.version }}
          tag_name: v${{ needs.check-tag.outputs.version }}
          files: |
            ${{ steps.build.outputs.tarball_name }}
    outputs:
      sha256_hash: ${{ steps.build.outputs.sha256_hash }}
      assets: ${{ steps.publish.outputs.assets }}


  update-feedstock-files:
    runs-on: ubuntu-latest
    needs: [check-tag, release]
    steps:
      - name: Clone the feedstock repository
        uses: actions/checkout@v4
        with:
          repository: 'harvenstar/sagemaker-code-editor-feedstock'
          ref: 'dev'
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Create a new dev branch
        run: |
          git checkout -b ${{ env.branch-name }}
      - name: Update meta.yaml
        run: |
          VERSION=${{ needs.check-tag.outputs.version }}
          sed -i "s/{% set version = \".*\" %}/{% set version = \"$VERSION\" %}/" recipe/meta.yaml

          URL="${{ fromJSON(needs.release.outputs.assets)[0].browser_download_url }}"
          sed -i "s|url: .*\.tar\.gz|url: $URL|" recipe/meta.yaml

          SHA256=${{ needs.release.outputs.sha256_hash }}
          sed -i "s|sha256: [0-9a-f]*|sha256: $SHA256|" recipe/meta.yaml
      - name: Run diff
        run: git diff
      
      #commit and push changes
      - name: Commit and push changes
        # This step commits the modified 'recipe/meta.yaml' file and pushes it to the remote feedstock repository.
        # - Git user name and email are configured for the commit.
        # - 'git add' stages the changes.
        # - 'git commit' creates a commit with a message including the new version.
        #   ' || echo "No changes to commit." ' prevents the workflow from failing if there are no changes (e.g., if re-running on same version with no actual file change).
        # - The current local branch (which is the dynamic branch, e.g., 'auto-update-vX.Y.Z') is pushed to the 'origin' remote.
        #   This creates the branch on the remote if it doesn't exist.
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add recipe/meta.yaml
          # Check if there are changes to commit to avoid error if meta.yaml is already up-to-date
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update recipe to v${{ needs.check-tag.outputs.version }}"
          fi
          # Get the current branch name (should be the dynamic one created earlier)
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Pushing changes to origin/${CURRENT_BRANCH}"
          git push origin ${CURRENT_BRANCH}

      - name: Create Pull Request
        # This step uses the 'peter-evans/create-pull-request' action to create a pull request
        # in your feedstock repository (harvenstar/sagemaker-code-editor-feedstock).
        # - 'token': Uses the PAT from secrets for authentication.
        # - 'branch': Explicitly set to the dynamic branch name created earlier.
        # - 'base': Specifies the target branch for the pull request (e.g., 'dev' in your fork).
        # - 'title': Sets the title of the pull request, including the new version.
        # - 'body': Sets the body of the pull request, detailing the automated changes.
        # - 'labels': Optionally applies labels to the pull request.
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          # Explicitly specify the head branch for the PR (the dynamic branch created in this job)
          branch: ${{ steps.create_branch.outputs.branch_name }}
          # The target branch in your harvenstar/sagemaker-code-editor-feedstock fork
          base: dev 
          title: "[Automated] Update recipe to v${{ needs.check-tag.outputs.version }}"
          body: |
            This is an automated pull request to update the feedstock recipe for sagemaker-code-editor.

            **Version:** ${{ needs.check-tag.outputs.version }}
            **Tarball URL:** ${{ fromJSON(needs.release.outputs.assets)[0].browser_download_url }}
            **SHA256:** ${{ needs.release.outputs.sha256_hash }}

            This PR was generated automatically by a GitHub Actions workflow.
          labels: automated-update, bot
          # assignees: harvenstar
          # reviewers: harvenstar
